version: 2
updates:
  - commit-message:
      prefix: "chore"
    directory: /
    package-ecosystem: gomod
    schedule:
      interval: weekly
    groups:
      golang-dependencies:
        patterns:
          - "*"
  - commit-message:
      prefix: "chore"
    directory: /
    package-ecosystem: docker
    schedule:
      interval: weekly
