#!/bin/sh

git config --global user.name "${GIT_CONFIG_USER_NAME-Mender Test Bot}"
git config --global user.email ${GIT_CONFIG_USER_EMAIL-mender@northern.tech}

ssh-keyscan github.com >> /root/.ssh/known_hosts
ssh-keyscan gitlab.com >> /root/.ssh/known_hosts

# If a GPG key was mounted into the container, import it and configure Git to use it
if [ -f "/root/gpg_key" ]; then
    gpg --import /root/gpg_key
    echo -e "[commit]\n\tgpgsign = true" >> ~/.gitconfig
fi

exec /integration-test-runner
