#!/bin/sh

git config --global user.name "${GIT_CONFIG_USER_NAME-Mender Test Bot}"
git config --global user.email ${GIT_CONFIG_USER_EMAIL-mender@northern.tech}

ssh-keyscan github.com >> /root/.ssh/known_hosts
ssh-keyscan gitlab.com >> /root/.ssh/known_hosts

exec /integration-test-runner
