// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	client_go "gitlab.com/gitlab-org/api/client-go"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// CancelPipelineBuild provides a mock function with given fields: path, id
func (_m *Client) CancelPipelineBuild(path string, id int64) error {
	ret := _m.Called(path, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int64) error); ok {
		r0 = rf(path, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreatePipeline provides a mock function with given fields: path, options
func (_m *Client) CreatePipeline(path string, options *client_go.CreatePipelineOptions) (*client_go.Pipeline, error) {
	ret := _m.Called(path, options)

	var r0 *client_go.Pipeline
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *client_go.CreatePipelineOptions) (*client_go.Pipeline, error)); ok {
		return rf(path, options)
	}
	if rf, ok := ret.Get(0).(func(string, *client_go.CreatePipelineOptions) *client_go.Pipeline); ok {
		r0 = rf(path, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client_go.Pipeline)
		}
	}

	if rf, ok := ret.Get(1).(func(string, *client_go.CreatePipelineOptions) error); ok {
		r1 = rf(path, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPipelineVariables provides a mock function with given fields: path, id
func (_m *Client) GetPipelineVariables(path string, id int64) ([]*client_go.PipelineVariable, error) {
	ret := _m.Called(path, id)

	var r0 []*client_go.PipelineVariable
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int64) ([]*client_go.PipelineVariable, error)); ok {
		return rf(path, id)
	}
	if rf, ok := ret.Get(0).(func(string, int64) []*client_go.PipelineVariable); ok {
		r0 = rf(path, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*client_go.PipelineVariable)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int64) error); ok {
		r1 = rf(path, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListProjectPipelines provides a mock function with given fields: path, options
func (_m *Client) ListProjectPipelines(path string, options *client_go.ListProjectPipelinesOptions) ([]*client_go.PipelineInfo, error) {
	ret := _m.Called(path, options)

	var r0 []*client_go.PipelineInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *client_go.ListProjectPipelinesOptions) ([]*client_go.PipelineInfo, error)); ok {
		return rf(path, options)
	}
	if rf, ok := ret.Get(0).(func(string, *client_go.ListProjectPipelinesOptions) []*client_go.PipelineInfo); ok {
		r0 = rf(path, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*client_go.PipelineInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(string, *client_go.ListProjectPipelinesOptions) error); ok {
		r1 = rf(path, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListPipelineJobs provides a mock function with given fields: path, pipelineID, options
func (_m *Client) ListPipelineJobs(path string, pipelineID int64, options *client_go.ListJobsOptions) ([]*client_go.Job, error) {
	ret := _m.Called(path, pipelineID, options)

	var r0 []*client_go.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int64, *client_go.ListJobsOptions) ([]*client_go.Job, error)); ok {
		return rf(path, pipelineID, options)
	}
	if rf, ok := ret.Get(0).(func(string, int64, *client_go.ListJobsOptions) []*client_go.Job); ok {
		r0 = rf(path, pipelineID, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*client_go.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int64, *client_go.ListJobsOptions) error); ok {
		r1 = rf(path, pipelineID, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PlayJob provides a mock function with given fields: path, jobID, options
func (_m *Client) PlayJob(path string, jobID int64, options *client_go.PlayJobOptions) (*client_go.Job, error) {
	ret := _m.Called(path, jobID, options)

	var r0 *client_go.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int64, *client_go.PlayJobOptions) (*client_go.Job, error)); ok {
		return rf(path, jobID, options)
	}
	if rf, ok := ret.Get(0).(func(string, int64, *client_go.PlayJobOptions) *client_go.Job); ok {
		r0 = rf(path, jobID, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client_go.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int64, *client_go.PlayJobOptions) error); ok {
		r1 = rf(path, jobID, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProtectRepositoryBranches provides a mock function with given fields: path, options
func (_m *Client) ProtectRepositoryBranches(path string, options *client_go.ProtectRepositoryBranchesOptions) (*client_go.ProtectedBranch, error) {
	ret := _m.Called(path, options)

	var r0 *client_go.ProtectedBranch
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *client_go.ProtectRepositoryBranchesOptions) (*client_go.ProtectedBranch, error)); ok {
		return rf(path, options)
	}
	if rf, ok := ret.Get(0).(func(string, *client_go.ProtectRepositoryBranchesOptions) *client_go.ProtectedBranch); ok {
		r0 = rf(path, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client_go.ProtectedBranch)
		}
	}

	if rf, ok := ret.Get(1).(func(string, *client_go.ProtectRepositoryBranchesOptions) error); ok {
		r1 = rf(path, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UnprotectRepositoryBranches provides a mock function with given fields: path, branch, options
func (_m *Client) UnprotectRepositoryBranches(path string, branch string, options client_go.RequestOptionFunc) (*client_go.Response, error) {
	ret := _m.Called(path, branch, options)

	var r0 *client_go.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, client_go.RequestOptionFunc) (*client_go.Response, error)); ok {
		return rf(path, branch, options)
	}
	if rf, ok := ret.Get(0).(func(string, string, client_go.RequestOptionFunc) *client_go.Response); ok {
		r0 = rf(path, branch, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client_go.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, client_go.RequestOptionFunc) error); ok {
		r1 = rf(path, branch, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteBranch provides a mock function with given fields: path, branch, options
func (_m *Client) DeleteBranch(path string, branch string, options *client_go.RequestOptionFunc) (*client_go.Response, error) {
	ret := _m.Called(path, branch, options)

	var r0 *client_go.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, *client_go.RequestOptionFunc) (*client_go.Response, error)); ok {
		return rf(path, branch, options)
	}
	if rf, ok := ret.Get(0).(func(string, string, *client_go.RequestOptionFunc) *client_go.Response); ok {
		r0 = rf(path, branch, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client_go.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, *client_go.RequestOptionFunc) error); ok {
		r1 = rf(path, branch, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
